# Generated by Django 2.2 on 2020-01-25 13:00

from django.db import migrations, models
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20200125_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_pub',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, verbose_name=django.db.models.fields.DateField),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(verbose_name='Pages'),
        ),
    ]
