# Generated by Django 2.2 on 2020-01-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20200125_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_pub',
        ),
    ]
