# Generated by Django 2.2 on 2020-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_remove_books_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
